spring:
  datasource:
    url: jdbc:mysql://localhost/hello_world?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: demo
  freemarker:
        suffix: .html
        charset: utf-8
mybatis: 
  mapper-locations:
  - classpath:com/example/demo/mapper/*.xml
  type-aliases-package: com.example.demo.entity
  
  
logging:
  level:
    com.eth.wallet.mapper: debug
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://127.0.0.1:9999/eureka

