server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://47.100.54.147/hello_world?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: demo
  freemarker:
        suffix: .html
        charset: utf-8
#spring.http.multipart.enabled=true #默认支持文件上传.  这是2.0以下的配置
  servlet:
    multipart:
      enabled: true     #默认支持文件上传.
      file-size-threshold: 0 #支持文件写入磁盘.
      location: D:/touxiang/ # 上传文件的临时目录
      max-file-size: 10MB # 最大支持文件大小
      max-request-size: 10MB # 最大支持请求大小
  resources:
    static-locations: classpath:static/, file:${spring.servlet.multipart.location}
  mvc:
    static-path-pattern: /**
mybatis: 
  mapper-locations:
  - classpath:com/example/demo/mapper/*.xml
  type-aliases-package: com.example.demo.entity
  
  
logging:
  level:
    com.eth.wallet.mapper: debug
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://127.0.0.1:9999/eureka

