spring:
  datasource:
    url: jdbc:mysql://localhost/jeecg?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: demo
    
mybatis: 
  mapper-locations:
  - classpath:com/example/demo/mapper/*.xml
  type-aliases-package: com.example.demo.entity
  
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://127.0.0.1:9999/eureka

