package com.example.demo.entity;

import java.util.Date;


import lombok.Getter;
import lombok.Setter;

/**
 * 
　 * <p>Title: UserEntity</p> 
　 * <p>Description: </p> 
　 * @author xiaobo 
　 * @date 2019年8月24日
 */
@Getter
@Setter
public class UserEntity implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 7915187367634807077L;
    /* This code was generated by TableGo tools, mark 1 begin. */
    /** id */
    private Long id;

    /** 用户名 */
    private String name;

    /** 密码 */
    private String password;

    /** 邮箱 */
    private String email;

    /** 头像 */
    private String touXiang;

    /** 姓名 */
    private String userName;

    /** 性别 */
    private String sex;

    /** 创建时间 */
    private Date createTime;

    /** 修改时间 */
    private Date updateTime;
    
    


}