package com.example.demo.entity.login;

import java.util.Date;

import lombok.Data;

/**
 * 
 * <p>
 * Title: UserEntity
 * </p>
 * <p>
 * Description:
 * </p>
 * 
 * @author xiaobo @date 2019年8月24日
 */
/*
 * @Getter
 * 
 * @Setter
 */
@Data
public class UserEntity implements java.io.Serializable {
	/** 版本号 */
	private static final long serialVersionUID = 7915187367634807077L;
	/* This code was generated by TableGo tools, mark 1 begin. */
	/** id */
	private Long userId;
	
	/** 微信id*/
	private String openId;

	/** 用户名 */
	private String name;

	/** 密码 */
	private String password;

	/** 邮箱 */
	private String email;
	
	/** 国家 */
	private String country;
	
	/** 省份 */
	private String province;
	
	/** 城市 */
	private String city;
	
	/** 头像 */
	private String touXiang;
	
	/**	是否微信用户 */
	private String isWxUser;

	/** 姓名 */
	private String userName;

	/** 性别 */
	private String sex;

	/** 生日 */
	private Date birthDay;

	/** 创建时间 */
	private Date createTime;

	/** 修改时间 */
	private Date updateTime;

	/** 自我介绍 */
	private String zwjs;
	/**验证码*/
	private String yzm;
}
